<?php

namespace ContainerWXvtOQY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_BaseEntityTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'ux.autocomplete.base_entity_type' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Form\BaseEntityAutocompleteType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['ux.autocomplete.base_entity_type'] = new \Symfony\UX\Autocomplete\Form\BaseEntityAutocompleteType(($container->services['router'] ?? self::getRouterService($container)));
    }
}
