<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXvtOQY\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXvtOQY/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerWXvtOQY.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerWXvtOQY\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerWXvtOQY\App_KernelProdContainer([
    'container.build_hash' => 'WXvtOQY',
    'container.build_id' => '69b65190',
    'container.build_time' => 1736187175,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXvtOQY');
