<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'ux_entity_autocomplete' => [['alias'], ['_controller' => 'ux.autocomplete.entity_autocomplete_controller'], [], [['variable', '/', '[^/]++', 'alias', true], ['text', '/autocomplete']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
    'App\Controller\IndexController::index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/index']], [], [], []],
];
