<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.0b03f9b2.js',
                '/build/939.91fd55ea.js',
                '/build/app.20536e2e.js',
            ],
            'css' => [
                '/build/app.f7134eda.css',
            ],
        ],
    ],
],

]];
