<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxG6XZG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxG6XZG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxG6XZG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxG6XZG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxG6XZG\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxG6XZG',
    'container.build_id' => 'd9ab81e5',
    'container.build_time' => 1736197980,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxG6XZG');
